spring:
  application:
    name: greething-service



management:
  endpoints:
    web:
      exposure:
        include:
          - "*"



greeting-service:
  greeting: "Oiiiiiii"
  default-value: "Mundo1"
